# Generated by Django 3.1.4 on 2020-12-03 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighboursapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hoodadminprofile',
            table='hoodadminProf',
        ),
    ]
