# Generated by Django 3.1.4 on 2020-12-03 16:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neighboursapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NeighborProfile',
            new_name='ResidentProfile',
        ),
    ]
