# Generated by Django 3.1.4 on 2020-12-03 19:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighboursapp', '0002_auto_20201203_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoodadminprofile',
            name='prof_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
