# Generated by Django 3.1.4 on 2020-12-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighboursapp', '0003_auto_20201203_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoodadminprofile',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='hoodadminprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
